{% set version = "0.8.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rdrop2
  version: {{ version|replace("-", "_") }}

source:
  fn: rdrop2_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rdrop2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rdrop2/rdrop2_{{ version }}.tar.gz
  sha256: b9add765fe8e7c966f0d36eef939a9e38f253958bd2a3c656b890cbb0366300b

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-assertive
    - r-digest
    - r-dplyr
    - r-httr
    - r-jsonlite
    - r-magrittr
    - r-purrr
  run:
    - r-base
    - r-assertive
    - r-digest
    - r-dplyr
    - r-httr
    - r-jsonlite
    - r-magrittr
    - r-purrr

test:
  commands:
    - $R -e "library('rdrop2')"           # [not win]
    - "\"%R%\" -e \"library('rdrop2')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rdrop2
  license: MIT
  summary: Provides full programmatic access to the 'Dropbox' file hosting platform <https://dropbox.com>, including support for all standard file operations.
  license_family: MIT

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
    - roryk
