travis:
  secure:
    BINSTAR_TOKEN: Ey7XTrHQEvUMlG4NdymZ0XMKYwNlM0T/DXjKN8sjXc924dLFAp4EUT66J6URJ1G92b2V3+PDUFleS7RvGaIQgDY7BSg23uowuUrGww+EO/Dq6/zzPaSH4TNAXJcEyqKjU7IFuusamQ8BUHenRcfIsIe0PwfASq9CbXe1Calzrx9umGecTU1HL6DIbhQOOO2RoITWUw0/fo2NGGaMQd92EQ5GcoMmnoCqwL4pbQlhSV0fyKRZDvxlUr7OZuLyhYSiOFcak3GUqwf65t+XAImT+fTcuaxEdT2fSjbhQHpdUoYCvIxczbp1eiCV95hDBuM0KOEPCC5rHp4Ariqz1jEANb06c7Xv0eO6d2JvuA6HnYz4G0SgmbAT52u7xcMq/5KEkE8xQi7yqmI94c1uNKHljfY6/Fod2fhSpmVmwj3Wc36q/pMt9wYd1j9rnIyBYjOs0Jhb8aSGADKZ8PGWiknw48SjNNotqZzdXa884MJ8rCC5In92aZ6qKjD9QAoFS+VIZtXpVWD/PQ4ZLDmkaatKtLSh/09xjDUC1qFtz3aBkk/uIT2Q8nc0hMuKoKL13b3UbjCeI8Y0rdvD5bxLsMtlMvyZm5kpoBEPwU83Ecv5VlpB3Bwac3r2+HDbnyihhlv8CsAeCC3MQ3xy0AwQJjeEFUSL9phE6ktJ4I+yFBCrqxE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
