appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: kSIq9oY4TmUaE1FMlqZB2GLiw3sbq6rWR+WWqxqxo0+Lua7RzWf0MtPmm3uvsF+6RtRM+hFzj/uFuLOR/ox0X6CX7QH3WGYMuoQFpC2m9xYon53w8n9bUgsFlyaIfhix4PfZQ+/I0Wb0LPZPiJgTUH2oxDLd7fAPRzswQkxWOzuYHTHUpOy5Qsm+6zUHkZzIyVUfzazgjVgL/l1knDpzu0GNXISVlDSFy/VpHxNh0LcMR0aad/7/jABTDuToX3r/XaSWVBONcfTDaYJDt0H8Ks8HhHCkTpzwEpBvW5ITna39px0+IYMCl2WZDvzyGp1LxSEvgeIQb2yZigOkapo9myQsNS3kgv0WD5SvXH1KuNtI0k6YW0ADF3lxqyCw5v1zLzwcNQV2NLhCFQRv5QMGzFICcB9brsElm/JVqvPNjJU9OaQL2xdd61hNjrNrYhHVKhA3vhpYjMThkLv6rE4D6S3SewhUwIDv2TfkI33LqRFqk7ODi0zcg+n+9ItJLAyNPesD/f+k5ANYUDv1dbaEz1PeeY/TEK8mTpF7NSbfasOwATfXvAtRPotHxTLDQ7EY3lA3VMBU0xewhQ+4ExGniv9NSuK0J6CrzVqfIu90H3eMy87M3XY38lk2Rf8b11j8BSzBi1fA8b+NLvH8/aWXcTWlp7EuRj3HzLjhMujqOCY=}
